### ISSUE TITLE
add date/time functions

### ISSUE THREAD

**Issue by johnstantongeddes** [vertica/vertica.dplyr#14]
I have a use-case where it'd be nice to have [Date/Time functions](https://my.vertica.com/docs/7.1.x/HTML/index.htm#Authoring/SQLReferenceManual/Functions/Date-Time/DateTimeFunctions-1.htm%3FTocPath%3DSQL%2520Reference%2520Manual%7CSQL%2520Functions%7CDate%252FTime%2520Functions%7C_____0) available via mutate.

For example,

```
q1 <- select(table, col1, col2, date)
q2 <- mutate(q1, M = month(date))
```

It seems like this should be possible using lubridate on the R end, and the defined Vertica date/time functions. I'm happy to work on this if you could give some pointers on where it'd best to implement.

Thanks for making this package available!

**Comment by shabbybanks** [comment]
Have you tried this? I would guess that `month` here would just get directly mapped to the vertica function of the same name.

**Comment by johnstantongeddes** [comment]
@shabbybanks I'm sure you're right but I used vertica.dplyr less than I hoped/anticipated as I find it's still easier for me to write the SQl separately and just use RJDBC to pull it into R.
