### ISSUE TITLE
Mutate creates system columns when used on local tbl

### ISSUE THREAD

**Issue by vladserkoff** [vertica/vertica.dplyr#3]
When used on local tables vertica.dplyr::mutate creates additional columns, which i suppose are meant to be invisible.

```
library(dplyr)
library(vertica.dplyr)

data_frame(x = 1:2) %>% mutate(y = 2 * x)
Source: local data frame [2 x 4]
  x .evalNames .collapse y
1 1      FALSE      TRUE 2
2 2      FALSE      TRUE 4

data_frame(x = 1:2) %>% dplyr::mutate(y = 2 * x)
Source: local data frame [2 x 2]
  x y
1 1 2
2 2 4
```

P.S. Thanks for the package!

**Comment by etduwx** [comment]
Hi @vladserkoff , thanks for reporting this issue.

I've pushed a quick fix. Could you verify that it's now resolved?

Thanks.

**Comment by vladserkoff** [comment]
@etduwx , that fixes it.
Thanks for quick response
