### ISSUE TITLE
dependency on HPdata?

### ISSUE THREAD

**Issue by hilaryparker** [vertica/vertica.dplyr#4]
Hi! I ran into an error suggesting that I might need to install the `HPdata` package, but I can't seem to find it (best guess was here: https://github.com/vertica/DistributedR/tree/master/algorithms/HPdata)

Here's my session_info() (running from RStudio Server) as well as the error I am getting

Error:

``` r
> vertica.dplyr::tbl2darray(vertica_odbc, "hparker.table")
Attempting to load package `HPdata` and its dependencies...
Error in value[[3L]](cond) : 
  Could not load one or more of HPdata and/or Distributed R and their dependencies. Please download: https://github.com/vertica/DistributedR/ 
```

Session Info:

``` r
> session_info()
Session info -----------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.447)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       UTC                         

Packages ---------------------------------------------------------------
 package         * version  date      
 assertthat      * 0.1      2013-12-06
 codetools         0.2-11   2015-03-10
 crayon            1.3.1    2015-07-13
 curl              0.9.1    2015-07-04
 DBI             * 0.3.1    2014-09-24
 devtools        * 1.8.0    2015-05-09
 digest            0.6.8    2014-12-31
 distributedR    * 1.2.0    2015-08-31
 dplyr           * 0.4.2    2015-06-16
 Executor        * 1.2.0    2015-08-31
 git2r             0.10.1   2015-05-07
 httr              1.0.0    2015-06-25
 lattice           0.20-31  2015-03-30
 magrittr          1.5      2014-11-22
 Matrix            1.2-1    2015-06-01
 memoise           0.2.1    2014-04-22
 ProjectTemplate * 0.6      2014-10-06
 R6                2.1.1    2015-08-19
 Rcpp            * 0.12.0   2015-07-25
 RInside         * 0.2.13   2015-05-20
 rJava           * 0.9-6    2013-12-24
 RJDBC           * 0.2-5    2014-12-19
 rstudioapi        0.3.1    2015-04-07
 rversions         1.0.1    2015-06-06
 stringi           0.5-5    2015-06-29
 stringr           1.0.0    2015-04-30
 testthat        * 0.10.0   2015-05-22
 vertica.dplyr   * 0.4.2    2015-08-31
 vRODBC          * 1.2.0    <NA>      
 XML             * 3.98-1.3 2015-06-30
 xml2              0.1.1    2015-06-02
 source                                
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 Github (vertica/DistributedR@9ac876a) 
 CRAN (R 3.2.0)                        
 Github (vertica/DistributedR@9ac876a) 
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.0)                        
 CRAN (R 3.2.1)                        
 Github (vertica/vertica.dplyr@4dfb2d2)
 Github (vertica/DistributedR@9ac876a) 
 CRAN (R 3.2.1)                        
 CRAN (R 3.2.0) 
```

**Comment by etduwx** [comment]
Hi @hilaryparker,

You're right, tbl2darray does indeed require that you have the HPdata package installed. The function is however, intended to be only used in conjunction with Distributed R (https://github.com/vertica/DistributedR), a distributed computation platform in R that allows you to run distributed algorithms in R (which, if you're not already using, I recommend you try out, if the scale of your problem is appropriate :)).

If you are only intending to get the data over to R on a single node, then you should use the collect() function on the table instead. In contrast, tbl2darray() will, if you're also using Distributed R, convert the tbl into a Distributed R darray object.

Hope this helps,
Edward

**Comment by hilaryparker** [comment]
Thanks @etduwx! Sorry for not supplying more context! So I do have the DistributedR package installed already as part of trying to connect to our Vertica cluster. 

I first tried `salaries <- tbl(vertica,"hparker.table")` and received the following error:

``` r
> salaries <- tbl(vertica,"hparker.table")
Error in dim.tbl_sql(x) : attempt to apply non-function
```

I then tried the `tbl2darray()` function somewhat randomly, and assumed that the error for both commands was with the missing `HPdata` package.

Would appreciate any help debugging!

**Comment by etduwx** [comment]
Hi @hilaryparker ,

Did you first create a connection to the DB using JDBC or ODBC? I'm guessing that you stored the src_vertica context in "vertica"?

Is "hparker.table" a table named "hparker.table" or a table named "table" under the "hparker" schema? Currently, non-public schema tables have better support in vertica.dplyr with an ODBC connection.

Thanks,
Edward

**Comment by hilaryparker** [comment]
Hi @etduwx, thanks again for your help!

Created the connection using ODBC, and yes saved the `src_vertica` output as `vertica`.

Got the desired results here:

``` r
> class(vertica)
[1] "src_vertica" "src_sql"     "src" 
```

`hparker.table` is a table "table" under the "hparker" schema.

**Comment by etduwx** [comment]
Interesting. Could you trigger the error again and do a traceback() to see a stack trace of what caused the error?

**Comment by hilaryparker** [comment]
Sure thing:

``` r
> salaries <- tbl(vertica,"hparker.temp_R_table")
Error in dim.tbl_sql(x) : attempt to apply non-function
> traceback()
7: dim.tbl_sql(x)
6: dim(x)
5: getdimensions(x)
4: update(tbl)
3: tbl_sql("vertica", src = src, from = from, ...)
2: tbl.src_vertica(vertica, "hparker.temp_R_table")
1: tbl(vertica, "hparker.temp_R_table")
```

**Comment by etduwx** [comment]
@hilaryparker ,

I know what the problem is. In Distributed R, you must have loaded the executor package, which exports another function called "update", overriding the stats::update generic function.

The wrong function is getting called. If you restart R and run that tbl command without loading DR, I am certain that it will work.

However, this other issue of conflicting namespace is something that we should look into. Thanks for helping discover this!

Let me know if running tbl without DR loaded works.

Thanks,
Ed

**Comment by etduwx** [comment]
FYI, I am looking into getting DistR's update function changed into a generic, which should resolve the namespace conflict.

**Comment by hilaryparker** [comment]
thank you!!! That did indeed solve the problem @etduwx. I'll continue to check back in as I'm working through our setup here.

**Comment by etduwx** [comment]
That's great, @hilaryparker .

In the meantime, we'll try to resolve this namespace problem with DistR. Hopefully, this won't be too much of a bother to you :). If it's a really big problem, a "band-aid" temporary solution might be to simply assign "update" the version of the function you want, i.e.:

update <- stats::update (when you want to use dplyr)
update <- Executor::update for DistR
