### ISSUE TITLE
Strange behavior on Vertica 7 with vertica.dplyr

### ISSUE THREAD

**Issue by earino** [vertica/vertica.dplyr#5]
I simply create a jdbc connection:

```
vertica_jdbc <- src_vertica(jdbcpath="lib/vertica-jdbc-7.1.2-0.jar",
                            dbname = "Dev",
                            host = "_________",
                            port = 5433,
                            user = "________",
                            password = "___________")
```

And then I try to run the following code:

```
vertica_jdbc %>% tbl("vst_notes.highlights") %>% summarise(count=n())
```

This returns the error message:

```
Source: Vertica JDBC Connection [______@____________:5433/Dev]
From: <derived table> [?? x 1]

Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT "count"
FROM (SELECT count(*) AS "count"
FROM "vst_notes.highlights") AS "zzz10"
LIMIT 10 ([Vertica][VJDBC](4566) ERROR: Relation "vst_notes.highlights" does not exist)
```

The reference to vst_notes.highlights in the subquery should not be quoted. If I remove the quotes it works perfectly fine.

**Comment by etduwx** [comment]
Hi Eduardo,

Currently schema tables don't work terribly well with JDBC (we will look to fixing this), so this is known. In the meantime, would it be possible to switch to vRODBC?

Thanks,
Edward

**Comment by earino** [comment]
I can probably switch to vRODBC without an issue, as long as it's supported on my mac :) Is there an example on how to do this from my mac anywhere? I would suggest you put a statement on the README regarding this limitation...

**Comment by earino** [comment]
I do have to ask though, should I not be using schema tables? is this not the appropriate way to be using Vertica "in the big picture"?

**Comment by etduwx** [comment]
Hi Eduardo,

You may refer to:
https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/ConnectingToHPVertica/InstallingDrivers/InstallingTheODBCDriverOnMacintoshOSX.htm

vRODBC may be installed from here: https://github.com/vertica/DistributedR/tree/master/vRODBC

I cannot comment on the appropriateness of using Schema tables :). Right now this is simply an issue with how vertica.dplyr handles escaping table names when connected with JDBC -- it does not handle the quoting properly, but it should work fine when connected with vRODBC. We may add a brief note in the README until this is fixed. 

Thanks,
Ed

**Comment by etduwx** [comment]
@earino,

We have just merged in some changes (thanks to @khotilov) that should much improve vertica.dplyr's handling of schema tables. Let us know if you continue to experience difficulties with regard to this issue. I will close this post for now.

Thanks.
